name: Check Proofs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set environment variables
      run: |
        echo "::set-env name=CACHE_BIN::$GITHUB_WORKSPACE/.cache/bin"
        echo "::set-env name=PATH::$GITHUB_WORKSPACE/.cache/bin:$PATH"
        echo "::set-env name=OPAMROOT::$GITHUB_WORKSPACE/.cache/.opam"
    - name: Cache Opam
      id: cache-opam
      uses: actions/cache@v1
      with:
        path: .cache
        key: opam-coq-8-11
    - name: install opam
      if: steps.cache-opam.outputs.cache-hit != 'true'
      run: |
        mkdir -p $CACHE_BIN
        cd $CACHE_BIN
        wget https://github.com/ocaml/opam/releases/download/2.0.6/opam-2.0.6-x86_64-linux
        mv opam-2.0.6-x86_64-linux opam
        chmod +x opam
    - name: Install coq
      if: steps.cache-opam.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install bubblewrap
        opam init -c 4.07.1
        eval $(opam env)
        opam repo add coq-released https://coq.inria.fr/opam/released
        opam install coq -y
        coqc --version
    - name: Check proofs with Coq
      run: |
        eval $(opam env)
        coqc --version
        cd $GITHUB_WORKSPACE
        coqc regex.v -verbose
